import { Roboto } from "next/font/google"
import "./globals.css"
import { Header } from "@/components/Header"
import { AppProvider } from "@/components/AppContext"

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <main className='max-w-4xl mx-auto px-4 pb-4'>
          <AppProvider>
            <Header />
            {children}
            <footer className='mt-16'>
              <p className='text-sm text-center text-gray-600 border-t pt-16'>
                &copy; 2024 All rights reserved
              </p>
            </footer>
            </AppProvider>
        </main>
      </body>
    </html>
  )
}
